### ISSUE TITLE
Exception: Could not parse the note: C#######################4

### ISSUE THREAD

**Issue by fferri** [gciruelos/musthe#13]
```
>>> from musthe.musthe import *
>>> scale(Note('F'), 'locrian')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    scale(Note('F'), 'locrian')
  File "[...]/musthe/musthe/musthe.py", line 26, in scale
    return [note] + [note+Interval(i) for i in scales[scale_name]]
  File "[...]/musthe/musthe/musthe.py", line 26, in <listcomp>
    return [note] + [note+Interval(i) for i in scales[scale_name]]
  File "[...]/musthe/musthe/musthe.py", line 118, in __add__
    return Note(new_note_tone+accidental+str(new_note_octave))
  File "[...]/musthe/musthe/musthe.py", line 57, in __init__
    raise Exception('Could not parse the note: '+note)
Exception: Could not parse the note: C#######################4
```

**Comment by fferri** [comment]
I think you can fix this by changing line 91-92 to:

```
        if difference < 3: difference += 12
        if difference > 3: difference -= 12
```

**Comment by fferri** [comment]
by the way, the code for Note.__add__ looks rather complicated. Wouldn't be easier to represent notes by their midi number, and then add intervals by simple arithmetic addition? Or is there some music theory aspect I'm missing there?

**Comment by gciruelos** [comment]
please do a pull request and i'll accept it.
thank you
